version: "3"
services:
  instaclone_node:
    restart: always
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./src:/app/src"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
